// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7a-PQ7Ah-CkkgczJ39HDHYVMyuSqMG0',
    appId: '1:190992776572:web:38d83ecc0bfcfcfb9678f9',
    messagingSenderId: '190992776572',
    projectId: 'doroos-khas',
    authDomain: 'doroos-khas.firebaseapp.com',
    storageBucket: 'doroos-khas.firebasestorage.app',
    measurementId: 'G-5JN9SMT325',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADzERh3rEnb6q5n5o-3T80-fr8oDNsSgw',
    appId: '1:190992776572:android:5a3128e79fd4c3449678f9',
    messagingSenderId: '190992776572',
    projectId: 'doroos-khas',
    storageBucket: 'doroos-khas.firebasestorage.app',
  );
}
